  xcodebuild_arguments: 
    - "-project"
    - "CoreCityOS/CoreCityOS.xcodeproj"
    - "-scheme"
    - "CoreCityOS iOS"
  swift_version: "2.1.1"
  author_name: "CityOS"
  author_url: "http://cityos.io"
  module_name: "CoreCityOS"
  readme_path: "CoreCityOS/README.md"
  root_url: "http://cityos.github.io/CoreCityOS/"
  github_url: "https://github.com/cityos/CoreCityOS"
  github_file_prefix: "https://github.com/cityos/CoreCityOS/tree/master"
  exclude: "~/core-ios/CoreCityOS/Sources/Operators.swift"
  theme: "fullwidth"
  custom_categories: 
    - 
      name: "Protocols"
      children: 
        - "LiveDataType"
        - "LiveDataCollectionType"
        - "FactoryType"
    -
      name: "Structs"
      children:
        - "DataPoint"
        - "LiveData"
        - "DataType"
        - "DeviceData"
    -
      name: "ErrorType definitions"
      children:
        - "SerializerError"
